site_name: Internal Documentation
nav:
  - Home: index.md
  - Compute on AI2:
      - Pre-requisites: compute-on-ai2/1-pre-requisites.md
      - Getting started: compute-on-ai2/2-getting-started.md
      - Running jobs: compute-on-ai2/3-running-jobs.md
  - ML infra:
      - Using Weights & Biases: ml-infra/1-using-wandb.md
  - Resources:
      - Beaker dashboard: https://beaker.allen.ai/
      - Beaker documentation: https://beaker-docs.apps.allenai.org/
theme:
  name: material
site_dir: site
